# Generated by Django 4.1.3 on 2023-01-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_jugador_fechanac_jugador_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Repuesto', models.CharField(max_length=40)),
                ('tipoderepuesto', models.CharField(max_length=40)),
                ('modeloderepuesto', models.CharField(max_length=40)),
                ('tipodevehiculo', models.CharField(max_length=40)),
                ('ano', models.DateField()),
                ('precio', models.IntegerField()),
                ('comprador', models.CharField(max_length=40)),
                ('proveedor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('ano', models.DateField()),
                ('status', models.CharField(max_length=40)),
                ('trabajosactivos', models.CharField(max_length=500)),
                ('trabajosporhacer', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
