# Generated by Django 4.1.3 on 2023-01-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_compras_taller_delete_equipo_delete_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('tipodeitem', models.CharField(max_length=40)),
                ('modelodeitem', models.CharField(max_length=40)),
                ('tipodevehiculo', models.CharField(max_length=40)),
                ('ano', models.DateField()),
                ('fechadecompra', models.DateField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('ultimoproveedor', models.CharField(max_length=40)),
                ('ultimocomprador', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=40)),
                ('fechadenac', models.DateField()),
                ('anodeingreso', models.DateField()),
                ('supervisordirecto', models.CharField(max_length=40)),
                ('sueldo', models.IntegerField()),
            ],
        ),
    ]
